<?php
/**
* @file
* A description of what your module does.
*/

/**
 * Implements hook_preprocess_page().
 */
function sticky_notes_preprocess_page(&$variables) {
  drupal_add_library('system', 'ui.draggable');
  drupal_add_js(drupal_get_path('module', 'sticky_notes') . '/json2.js');
  drupal_add_js(drupal_get_path('module', 'sticky_notes') . '/sticky_notes.js');
  drupal_add_css(drupal_get_path('module', 'sticky_notes') . '/sticky_notes.css');
  drupal_add_js('jQuery(document).ready(function () { STICKIES.open(); });', 'inline');
}
